# -*- coding: utf-8 -*-
"""test1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WIONwEkk5i15orPju104u9SSETcgrPP8
"""

# train_data = [
#     ('Software Engineer', 'Engineer'),
#     ('Senior Software Engineer', 'Software Engineer'),
#     ('Web Programmer', 'Programmer'),
#     ('UI Designer', 'Designer'),
#     ('エンジニア', 'Engineer'),
#     ('Engineer', 'エンジニア')
# ]
# labels = ['Software Engineer','Engineer','Senior Software Engineer','Web Programmer','Programmer']

# pip install plotly==2.7.0

from gensim.models.poincare import PoincareModel
from gensim.viz.poincare import poincare_2d_visualization
from IPython import display
from plotly.offline import init_notebook_mode, iplot
import pandas as pd

# init_notebook_mode(connected=True)

# import csv

# # ファイルオープン
# f = open('output.csv', 'w')
# writer = csv.writer(f, lineterminator='\n')

# # データをリストに保持
# csvlists = [
#     ['Software Engineer', 'Engineer'],
#     ['Senior Software Engineer', 'Software Engineer'],
#     ['Web Programmer', 'Programmer'],
#     ['UI Designer', 'Designer'],
#     ['エンジニア', 'Engineer'],
#     ['Engineer', 'エンジニア'],
# ]


# # 出力
# for csvlist in csvlists:
#     writer.writerow(csvlist)

# # ファイルクローズ
# f.close()

# occupation_relations_list = [(a, b) for a, b in pd.read_csv('output.csv', header=None).values]

# occupation_relations_list

from gensim.models.poincare import PoincareModel, PoincareRelations
from gensim.test.utils import datapath
relations = PoincareRelations(file_path=datapath('poincare_hypernyms_large.tsv'))

model = PoincareModel(relations, size=2)
model.train(epochs=100)

import plotly
import gensim.viz.poincare

# plotly.offline.init_notebook_mode(connected=False)
relations_set = set(relations)
figure_title = ""
plotly.offline.iplot(poincare_2d_visualization(model, relations_set, figure_title, num_nodes=None, show_node_labels=model.kv.vocab.keys()))
